var countries =  {
	"Afghanistan": {id: 4, visited: false, continent: "Asia"},
	"Albania": {id: 8, visited: false, continent: "Europe"},
	"Antarctica": {id: 10, visited: false, continent: "Antarctica"},
	"Algeria": {id: 12, visited: false, continent: "Africa"},
	"American Samoa": {id: 16, visited: false, continent: "Oceania"},
	"Andorra": {id: 20, visited: false, continent: "Europe"},
	"Angola": {id: 24, visited: false, continent: "Africa"},
	"Antigua": {id: 28, visited: false, continent: "North America"},
	"Barbuda": {id: 29, visited: false, continent: "North America"},
	"Azerbaijan": {id: 31, visited: false, continent: "Europe"},
	"Argentina": {id: 32, visited: false, continent: "South America"},
	"Australia": {id: 36, visited: false, continent: "Oceania"},
	"Austria": {id: 40, visited: false, continent: "Europe"},
	"Bahamas": {id: 44, visited: false, continent: "North America"},
	"Bahrain": {id: 48, visited: false, continent: "Asia"},
	"Bangladesh": {id: 50, visited: false, continent: "Asia"},
	"Armenia": {id: 51, visited: false, continent: "Europe"},
	"Barbados": {id: 52, visited: false, continent: "North America"},
	"Belgium": {id: 56, visited: false, continent: "Europe"},
	"Bermuda": {id: 60, visited: false, continent: "North America"},
	"Bhutan": {id: 64, visited: false, continent: "Asia"},
	"Bolivia, Plurinational State of": {id: 68, visited: false, continent: "South America"},
	"Bosnia and Herzegovina": {id: 70, visited: false, continent: "Europe"},
	"Botswana": {id: 72, visited: false, continent: "Africa"},
	"Brazil": {id: 76, visited: false, continent: "South America"},
	"Belize": {id: 84, visited: false, continent: "North America"},
	"British Indian Ocean Territory": {id: 86, visited: false, continent: "Asia"},
	"Solomon Islands": {id: 90, visited: false, continent: "Oceania"},
	"Virgin Islands, British": {id: 92, visited: false, continent: "North America"},
	"Brunei Darussalam": {id: 96, visited: false, continent: "Asia"},
	"Bulgaria": {id: 100, visited: false, continent: "Europe"},
	"Myanmar": {id: 104, visited: false, continent: "Asia"},
	"Burundi": {id: 108, visited: false, continent: "Africa"},
	"Belarus": {id: 112, visited: false, continent: "Europe"},
	"Cambodia": {id: 116, visited: false, continent: "Asia"},
	"Cameroon": {id: 120, visited: false, continent: "Africa"},
	"Canada": {id: 124, visited: false, continent: "North America"},
	"Cabo Verde": {id: 132, visited: false, continent: "Africa"},
	"Cayman Islands": {id: 136, visited: false, continent: "North America"},
	"Central African Republic": {id: 140, visited: false, continent: "Africa"},
	"Sri Lanka": {id: 144, visited: false, continent: "Asia"},
	"Chad": {id: 148, visited: false, continent: "Africa"},
	"Chile": {id: 152, visited: false, continent: "South America"},
	"China": {id: 156, visited: false, continent: "Asia"},
	"Taiwan, Province of China": {id: 158, visited: false, continent: "Asia"},
	"Christmas Island": {id: 162, visited: false, continent: "Oceania"},
	"Cocos (Keeling) Islands": {id: 166, visited: false, continent: "Oceania"},
	"Colombia": {id: 170, visited: false, continent: "South America"},
	"Comoros": {id: 174, visited: false, continent: "Africa"},
	"Mayotte": {id: 175, visited: false, continent: "Europe"},
	"Congo": {id: 178, visited: false, continent: "Africa"},
	"Congo, the Democratic Republic of the": {id: 180, visited: false, continent: "Africa"},
	"Cook Islands": {id: 184, visited: false, continent: "Oceania"},
	"Costa Rica": {id: 188, visited: false, continent: "North America"},
	"Croatia": {id: 191, visited: false, continent: "Europe"},
	"Cuba": {id: 192, visited: false, continent: "North America"},
	"Cyprus": {id: 196, visited: false, continent: "Europe"},
	"Czech Republic": {id: 203, visited: false, continent: "Europe"},
	"Benin": {id: 204, visited: false, continent: "Africa"},
	"Denmark": {id: 208, visited: false, continent: "Europe"},
	"Dominica": {id: 212, visited: false, continent: "North America"},
	"Dominican Republic": {id: 214, visited: false, continent: "North America"},
	"Ecuador": {id: 218, visited: false, continent: "South America"},
	"El Salvador": {id: 222, visited: false, continent: "North America"},
	"Equatorial Guinea": {id: 226, visited: false, continent: "Africa"},
	"Ethiopia": {id: 231, visited: false, continent: "Africa"},
	"Eritrea": {id: 232, visited: false, continent: "Africa"},
	"Estonia": {id: 233, visited: false, continent: "Europe"},
	"Faroe Islands": {id: 234, visited: false, continent: "Europe"},
	"Falkland Islands (Malvinas)": {id: 238, visited: false, continent: "South America"},
	"South Georgia and the South Sandwich Islands": {id: 239, visited: false, continent: "South America"},
	"Fiji": {id: 242, visited: false, continent: "Oceania"},
	"Finland": {id: 246, visited: false, continent: "Europe"},
	"Åland Islands": {id: 248, visited: false, continent: "Europe"},
	"France": {id: 250, visited: false, continent: "Europe"},
	"French Guiana": {id: 254, visited: false, continent: "South America"},
	"French Polynesia": {id: 258, visited: false, continent: "Oceania"},
	"French Southern Territories": {id: 260, visited: false, continent: "Oceania"},
	"Djibouti": {id: 262, visited: false, continent: "Africa"},
	"Gabon": {id: 266, visited: false, continent: "Africa"},
	"Georgia (Country)": {id: 268, visited: false, continent: "Europe"},
	"Gambia": {id: 270, visited: false, continent: "Africa"},
	"Palestine, State of": {id: 275, visited: false, continent: "Asia"},
	"Germany": {id: 276, visited: false, continent: "Europe"},
	"Ghana": {id: 288, visited: false, continent: "Africa"},
	"Gibraltar": {id: 292, visited: false, continent: "Europe"},
	"Kiribati": {id: 296, visited: false, continent: "Oceania"},
	"Greece": {id: 300, visited: false, continent: "Europe"},
	"Greenland": {id: 304, visited: false, continent: "North America"},
	"Grenada": {id: 308, visited: false, continent: "North America"},
	"Guadeloupe": {id: 312, visited: false, continent: "North America"},
	"Guam": {id: 316, visited: false, continent: "Oceania"},
	"Guatemala": {id: 320, visited: false, continent: "North America"},
	"Guinea": {id: 324, visited: false, continent: "Africa"},
	"Guyana": {id: 328, visited: false, continent: "South America"},
	"Haiti": {id: 332, visited: false, continent: "North America"},
	"Heard Island and McDonald Islands": {id: 334, visited: false, continent: "Oceania"},
	"Honduras": {id: 340, visited: false, continent: "North America"},
	"Hong Kong": {id: 344, visited: false, continent: "Asia"},
	"Hungary": {id: 348, visited: false, continent: "Europe"},
	"Iceland": {id: 352, visited: false, continent: "Europe"},
	"India": {id: 356, visited: false, continent: "Asia"},
	"Indonesia": {id: 360, visited: false, continent: "Asia"},
	"Iran": {id: 364, visited: false, continent: "Asia"},
	"Iraq": {id: 368, visited: false, continent: "Asia"},
	"Ireland": {id: 372, visited: false, continent: "Europe"},
	"Israel": {id: 376, visited: false, continent: "Asia"},
	"Italy": {id: 380, visited: false, continent: "Europe"},
	"Côte d'Ivoire": {id: 384, visited: false, continent: "Africa"},
	"Jamaica": {id: 388, visited: false, continent: "North America"},
	"Japan": {id: 392, visited: false, continent: "Asia"},
	"Kazakhstan": {id: 398, visited: false, continent: "Asia"},
	"Jordan": {id: 400, visited: false, continent: "Asia"},
	"Kenya": {id: 404, visited: false, continent: "Africa"},
	"North Korea": {id: 408, visited: false, continent: "Asia"},
	"South Korea": {id: 410, visited: false, continent: "Asia"},
	"Kuwait": {id: 414, visited: false, continent: "Asia"},
	"Kyrgyzstan": {id: 417, visited: false, continent: "Asia"},
	"Laos": {id: 418, visited: false, continent: "Asia"},
	"Lebanon": {id: 422, visited: false, continent: "Asia"},
	"Lesotho": {id: 426, visited: false, continent: "Africa"},
	"Latvia": {id: 428, visited: false, continent: "Europe"},
	"Liberia": {id: 430, visited: false, continent: "Africa"},
	"Libya": {id: 434, visited: false, continent: "Africa"},
	"Liechtenstein": {id: 438, visited: false, continent: "Europe"},
	"Lithuania": {id: 440, visited: false, continent: "Europe"},
	"Luxembourg": {id: 442, visited: false, continent: "Europe"},
	"Macao": {id: 446, visited: false, continent: "Europe"},
	"Madagascar": {id: 450, visited: false, continent: "Africa"},
	"Malawi": {id: 454, visited: false, continent: "Africa"},
	"Malaysia": {id: 458, visited: false, continent: "Asia"},
	"Maldives": {id: 462, visited: false, continent: "Asia"},
	"Mali": {id: 466, visited: false, continent: "Africa"},
	"Malta": {id: 470, visited: false, continent: "Europe"},
	"Martinique": {id: 474, visited: false, continent: "North America"},
	"Mauritania": {id: 478, visited: false, continent: "Africa"},
	"Mauritius": {id: 480, visited: false, continent: "Africa"},
	"Mexico": {id: 484, visited: false, continent: "North America"},
	"Monaco": {id: 492, visited: false, continent: "Europe"},
	"Mongolia": {id: 496, visited: false, continent: "Asia"},
	"Moldova, Republic of": {id: 498, visited: false, continent: "Europe"},
	"Montenegro": {id: 499, visited: false, continent: "Europe"},
	"Montserrat": {id: 500, visited: false, continent: "North America"},
	"Morocco": {id: 504, visited: false, continent: "Africa"},
	"Mozambique": {id: 508, visited: false, continent: "Africa"},
	"Oman": {id: 512, visited: false, continent: "Asia"},
	"Namibia": {id: 516, visited: false, continent: "Africa"},
	"Nauru": {id: 520, visited: false, continent: "Oceania"},
	"Nepal": {id: 524, visited: false, continent: "Asia"},
	"Netherlands": {id: 528, visited: false, continent: "Europe"},
	"Curaçao": {id: 531, visited: false, continent: "South America"},
	"Aruba": {id: 533, visited: false, continent: "South America"},
	"Sint Maarten (Dutch part)": {id: 534, visited: false, continent: "North America"},
	"Bonaire": {id: 535, visited: false, continent: "South America"},
	"Sint Eustatius": {id: 536, visited: false, continent: "North America"},
	"Saba": {id: 537, visited: false, continent: "North America"},
	"New Caledonia": {id: 540, visited: false, continent: "Oceania"},
	"Vanuatu": {id: 548, visited: false, continent: "Oceania"},
	"New Zealand": {id: 554, visited: false, continent: "Oceania"},
	"Nicaragua": {id: 558, visited: false, continent: "North America"},
	"Niger": {id: 562, visited: false, continent: "Africa"},
	"Nigeria": {id: 566, visited: false, continent: "Africa"},
	"Niue": {id: 570, visited: false, continent: "Oceania"},
	"Norfolk Island": {id: 574, visited: false, continent: "Oceania"},
	"Norway": {id: 578, visited: false, continent: "Europe"},
	"Northern Mariana Islands": {id: 580, visited: false, continent: "Oceania"},
	"Micronesia, Federated States of": {id: 583, visited: false, continent: "Oceania"},
	"Marshall Islands": {id: 584, visited: false, continent: "Oceania"},
	"Palau": {id: 585, visited: false, continent: "Oceania"},
	"Pakistan": {id: 586, visited: false, continent: "Asia"},
	"Panama": {id: 591, visited: false, continent: "North America"},
	"Papua New Guinea": {id: 598, visited: false, continent: "Oceania"},
	"Paraguay": {id: 600, visited: false, continent: "South America"},
	"Peru": {id: 604, visited: false, continent: "South America"},
	"Philippines": {id: 608, visited: false, continent: "Asia"},
	"Pitcairn": {id: 612, visited: false, continent: "Oceania"},
	"Poland": {id: 616, visited: false, continent: "Europe"},
	"Portugal": {id: 620, visited: false, continent: "Europe"},
	"Guinea-Bissau": {id: 624, visited: false, continent: "Africa"},
	"Timor-Leste": {id: 626, visited: false, continent: "Asia"},
	"Puerto Rico": {id: 630, visited: false, continent: "North America"},
	"Qatar": {id: 634, visited: false, continent: "Asia"},
	"Romania": {id: 642, visited: false, continent: "Europe"},
	"Russia": {id: 643, visited: false, continent: "Asia"},
	"Rwanda": {id: 646, visited: false, continent: "Africa"},
	"Saint Barthélemy": {id: 652, visited: false, continent: "North America"},
	"Saint Helena, Ascension and Tristan da Cunha": {id: 654, visited: false, continent: "South America"},
	"Saint Kitts and Nevis": {id: 659, visited: false, continent: "North America"},
	"Anguilla": {id: 660, visited: false, continent: "North America"},
	"Saint Lucia": {id: 662, visited: false, continent: "North America"},
	"Saint Martin (French part)": {id: 663, visited: false, continent: "North America"},
	"Saint Pierre and Miquelon": {id: 666, visited: false, continent: "North America"},
	"Saint Vincent and the Grenadines": {id: 670, visited: false, continent: "North America"},
	"San Marino": {id: 674, visited: false, continent: "Europe"},
	"Sao Tome and Principe": {id: 678, visited: false, continent: "Africa"},
	"Saudi Arabia": {id: 682, visited: false, continent: "Asia"},
	"Senegal": {id: 686, visited: false, continent: "Africa"},
	"Serbia": {id: 688, visited: false, continent: "Europe"},
	"Seychelles": {id: 690, visited: false, continent: "Africa"},
	"Sierra Leone": {id: 694, visited: false, continent: "Africa"},
	"Singapore": {id: 702, visited: false, continent: "Asia"},
	"Slovakia": {id: 703, visited: false, continent: "Europe"},
	"Vietnam": {id: 704, visited: false, continent: "Asia"},
	"Slovenia": {id: 705, visited: false, continent: "Europe"},
	"Somalia": {id: 706, visited: false, continent: "Africa"},
	"South Africa": {id: 710, visited: false, continent: "Africa"},
	"Zimbabwe": {id: 716, visited: false, continent: "Africa"},
	"Spain": {id: 724, visited: false, continent: "Europe"},
	"South Sudan": {id: 728, visited: false, continent: "Africa"},
	"Sudan": {id: 729, visited: false, continent: "Africa"},
	"Western Sahara": {id: 732, visited: false, continent: "Africa"},
	"Suriname": {id: 740, visited: false, continent: "South America"},
	"Svalbard and Jan Mayen": {id: 744, visited: false, continent: "Europe"},
	"Swaziland": {id: 748, visited: false, continent: "Africa"},
	"Sweden": {id: 752, visited: false, continent: "Europe"},
	"Switzerland": {id: 756, visited: false, continent: "Europe"},
	"Syrian Arab Republic": {id: 760, visited: false, continent: "Asia"},
	"Tajikistan": {id: 762, visited: false, continent: "Asia"},
	"Thailand": {id: 764, visited: false, continent: "Asia"},
	"Togo": {id: 768, visited: false, continent: "Africa"},
	"Tonga": {id: 776, visited: false, continent: "Oceania"},
	"Trinidad and Tobago": {id: 780, visited: false, continent: "South America"},
	"United Arab Emirates": {id: 784, visited: false, continent: "Asia"},
	"Tunisia": {id: 788, visited: false, continent: "Africa"},
	"Turkey (Europe)": {id: 792, visited: false, continent: "Europe"},
	"Turkey (Asia)": {id: 793, visited: false, continent: "Asia"},
	"Turkmenistan": {id: 795, visited: false, continent: "Asia"},
	"Turks and Caicos Islands": {id: 796, visited: false, continent: "North America"},
	"Tuvalu": {id: 798, visited: false, continent: "Oceania"},
	"Uganda": {id: 800, visited: false, continent: "Africa"},
	"Ukraine": {id: 804, visited: false, continent: "Europe"},
	"Macedonia": {id: 807, visited: false, continent: "Europe"},
	"Egypt": {id: 818, visited: false, continent: "Africa"},
	"United Kingdom": {id: 826, visited: false, continent: "Europe"},
	"Guernsey": {id: 831, visited: false, continent: "Europe"},
	"Jersey": {id: 832, visited: false, continent: "Europe"},
	"Isle of Man": {id: 833, visited: false, continent: "Europe"},
	"Tanzania": {id: 834, visited: false, continent: "Africa"},
	"Virgin Islands, US": {id: 850, visited: false, continent: "North America"},
	"Burkina Faso": {id: 854, visited: false, continent: "Africa"},
	"Uruguay": {id: 858, visited: false, continent: "South America"},
	"Uzbekistan": {id: 860, visited: false, continent: "Asia"},
	"Venezuela, Bolivarian Republic of": {id: 862, visited: false, continent: "South America"},
	"Wallis and Futuna": {id: 876, visited: false, continent: "Oceania"},
	"Samoa": {id: 882, visited: false, continent: "Oceania"},
	"Yemen": {id: 887, visited: false, continent: "Asia"},
	"Zambia": {id: 894, visited: false, continent: "Africa"},
	"Corsica": {id: 900, visited: false, continent: "Europe"},
	"Reunion": {id: 901, visited: false, continent: "Africa"},
	"Kosovo": {id: 902, visited: false, continent: "Europe"}
}

var states = {
	"Alabama":{"id":"01","visited":false},
	"Alaska": {"id":"02","visited":false},
	"Arizona":{"id":"04","visited":false},
	"Arkansas":{"id":"05","visited":false},
	"California":{"id":"06","visited":false},
	"Colorado":{"id":"08","visited":false},
	"Connecticut":{"id":"09","visited":false},
	"Delaware":{"id":"10","visited":false},
	"Florida":{"id":"12","visited":false},
	"Georgia (US state)":{"id":"13","visited":false},
	"Hawaii":{"id":"15","visited":false},
	"Idaho":{"id":"16","visited":false},
	"Illinois":{"id":"17","visited":false},
	"Indiana":{"id":"18","visited":false},
	"Iowa":{"id":"19","visited":false},
	"Kansas":{"id":"20","visited":false},
	"Kentucky":{"id":"21","visited":false},
	"Louisiana":{"id":"22","visited":false},
	"Maine":{"id":"23","visited":false},
	"Maryland":{"id":"24","visited":false},
	"Massachusetts":{"id":"25","visited":false},
	"Michigan":{"id":"26","visited":false},
	"Minnesota":{"id":"27","visited":false},
	"Mississippi":{"id":"28","visited":false},
	"Missouri":{"id":"29","visited":false},
	"Montana":{"id":"30","visited":false},
	"Nebraska":{"id":"31","visited":false},
	"Nevada":{"id":"32","visited":false},
	"New Hampshire":{"id":"33","visited":false},
	"New Jersey":{"id":"34","visited":false},
	"New Mexico":{"id":"35","visited":false},
	"New York":{"id":"36","visited":false},
	"North Carolina":{"id":"37","visited":false},
	"North Dakota":{"id":"38","visited":false},
	"Ohio":{"id":"39","visited":false},
	"Oklahoma":{"id":"40","visited":false},
	"Oregon":{"id":"41","visited":false},
	"Pennsylvania":{"id":"42","visited":false},
	"Rhode Island":{"id":"44","visited":false},
	"South Carolina":{"id":"45","visited":false},
	"South Dakota":{"id":"46","visited":false},
	"Tennessee":{"id":"47","visited":false},
	"Texas":{"id":"48","visited":false},
	"Utah":{"id":"49","visited":false},
	"Vermont":{"id":"50","visited":false},
	"Virginia":{"id":"51","visited":false},
	"Washington":{"id":"53","visited":false},
	"West Virginia":{"id":"54","visited":false},
	"Wisconsin":{"id":"55","visited":false},
	"Wyoming":{"id":"56","visited":false}
}

var continents = {
	"Africa": 0,
	"Asia": 0,
	"Europe": 0,
	"North America": 0,
	"Oceania": 0,
	"South America": 0,
	"Antarctica": 0
}

var jv_countries = {"Afghanistan":{"id":4,"visited":false,"continent":"Asia"},"Albania":{"id":8,"visited":false,"continent":"Europe"},"Antarctica":{"id":10,"visited":false,"continent":"Antarctica"},"Algeria":{"id":12,"visited":false,"continent":"Africa"},"American Samoa":{"id":16,"visited":false,"continent":"Oceania"},"Andorra":{"id":20,"visited":false,"continent":"Europe"},"Angola":{"id":24,"visited":false,"continent":"Africa"},"Antigua":{"id":28,"visited":true,"continent":"North America"},"Barbuda":{"id":29,"visited":false,"continent":"North America"},"Azerbaijan":{"id":31,"visited":false,"continent":"Europe"},"Argentina":{"id":32,"visited":false,"continent":"South America"},"Australia":{"id":36,"visited":false,"continent":"Oceania"},"Austria":{"id":40,"visited":false,"continent":"Europe"},"Bahamas":{"id":44,"visited":true,"continent":"North America"},"Bahrain":{"id":48,"visited":false,"continent":"Asia"},"Bangladesh":{"id":50,"visited":false,"continent":"Asia"},"Armenia":{"id":51,"visited":false,"continent":"Europe"},"Barbados":{"id":52,"visited":true,"continent":"North America"},"Belgium":{"id":56,"visited":false,"continent":"Europe"},"Bermuda":{"id":60,"visited":true,"continent":"North America"},"Bhutan":{"id":64,"visited":false,"continent":"Asia"},"Bolivia, Plurinational State of":{"id":68,"visited":false,"continent":"South America"},"Bosnia and Herzegovina":{"id":70,"visited":false,"continent":"Europe"},"Botswana":{"id":72,"visited":false,"continent":"Africa"},"Brazil":{"id":76,"visited":false,"continent":"South America"},"Belize":{"id":84,"visited":true,"continent":"North America"},"British Indian Ocean Territory":{id:86,visited:false,continent:"Asia"},"Solomon Islands":{"id":90,"visited":false,"continent":"Oceania"},"Virgin Islands, British":{"id":92,"visited":true,"continent":"North America"},"Brunei Darussalam":{"id":96,"visited":false,"continent":"Asia"},"Bulgaria":{"id":100,"visited":false,"continent":"Europe"},"Myanmar":{"id":104,"visited":false,"continent":"Asia"},"Burundi":{"id":108,"visited":false,"continent":"Africa"},"Belarus":{"id":112,"visited":false,"continent":"Europe"},"Cambodia":{"id":116,"visited":false,"continent":"Asia"},"Cameroon":{"id":120,"visited":false,"continent":"Africa"},"Canada":{"id":124,"visited":true,"continent":"North America"},"Cabo Verde":{"id":132,"visited":false,"continent":"Africa"},"Cayman Islands":{"id":136,"visited":true,"continent":"North America"},"Central African Republic":{"id":140,"visited":false,"continent":"Africa"},"Sri Lanka":{"id":144,"visited":false,"continent":"Asia"},"Chad":{"id":148,"visited":false,"continent":"Africa"},"Chile":{"id":152,"visited":false,"continent":"South America"},"China":{"id":156,"visited":false,"continent":"Asia"},"Taiwan, Province of China":{"id":158,"visited":false,"continent":"Asia"},"Christmas Island":{"id":162,"visited":false,"continent":"Oceania"},"Cocos (Keeling) Islands":{"id":166,"visited":false,"continent":"Oceania"},"Colombia":{"id":170,"visited":false,"continent":"South America"},"Comoros":{"id":174,"visited":false,"continent":"Africa"},"Mayotte":{"id":175,"visited":false,"continent":"Europe"},"Congo":{"id":178,"visited":false,"continent":"Africa"},"Congo, the Democratic Republic of the":{"id":180,"visited":false,"continent":"Africa"},"Cook Islands":{"id":184,"visited":false,"continent":"Oceania"},"Costa Rica":{"id":188,"visited":true,"continent":"North America"},"Croatia":{"id":191,"visited":false,"continent":"Europe"},"Cuba":{"id":192,"visited":false,"continent":"North America"},"Cyprus":{"id":196,"visited":false,"continent":"Europe"},"Czech Republic":{"id":203,"visited":false,"continent":"Europe"},"Benin":{"id":204,"visited":false,"continent":"Africa"},"Denmark":{"id":208,"visited":false,"continent":"Europe"},"Dominica":{"id":212,"visited":false,"continent":"North America"},"Dominican Republic":{"id":214,"visited":false,"continent":"North America"},"Ecuador":{"id":218,"visited":false,"continent":"South America"},"El Salvador":{"id":222,"visited":false,"continent":"North America"},"Equatorial Guinea":{"id":226,"visited":false,"continent":"Africa"},"Ethiopia":{"id":231,"visited":false,"continent":"Africa"},"Eritrea":{"id":232,"visited":false,"continent":"Africa"},"Estonia":{"id":233,"visited":false,"continent":"Europe"},"Faroe Islands":{"id":234,"visited":false,"continent":"Europe"},"Falkland Islands (Malvinas)":{"id":238,"visited":false,"continent":"South America"},"South Georgia and the South Sandwich Islands":{"id":239,"visited":false,"continent":"South America"},"Fiji":{"id":242,"visited":false,"continent":"Oceania"},"Finland":{"id":246,"visited":false,"continent":"Europe"},"Åland Islands":{"id":248,"visited":false,"continent":"Europe"},"France":{"id":250,"visited":false,"continent":"Europe"},"French Guiana":{"id":254,"visited":false,"continent":"South America"},"French Polynesia":{"id":258,"visited":false,"continent":"Oceania"},"French Southern Territories":{"id":260,"visited":false,"continent":"Oceania"},"Djibouti":{"id":262,"visited":false,"continent":"Africa"},"Gabon":{"id":266,"visited":false,"continent":"Africa"},"Georgia (Country)":{"id":268,"visited":false,"continent":"Europe"},"Gambia":{"id":270,"visited":false,"continent":"Africa"},"Palestine, State of":{"id":275,"visited":false,"continent":"Asia"},"Germany":{"id":276,"visited":false,"continent":"Europe"},"Ghana":{"id":288,"visited":false,"continent":"Africa"},"Gibraltar":{"id":292,"visited":false,"continent":"Europe"},"Kiribati":{"id":296,"visited":false,"continent":"Oceania"},"Greece":{"id":300,"visited":true,"continent":"Europe"},"Greenland":{"id":304,"visited":false,"continent":"North America"},"Grenada":{"id":308,"visited":false,"continent":"North America"},"Guadeloupe":{"id":312,"visited":false,"continent":"North America"},"Guam":{"id":316,"visited":false,"continent":"Oceania"},"Guatemala":{"id":320,"visited":false,"continent":"North America"},"Guinea":{"id":324,"visited":false,"continent":"Africa"},"Guyana":{"id":328,"visited":false,"continent":"South America"},"Haiti":{"id":332,"visited":true,"continent":"North America"},"Heard Island and McDonald Islands":{"id":334,"visited":false,"continent":"Oceania"},"Honduras":{"id":340,"visited":true,"continent":"North America"},"Hong Kong":{"id":344,"visited":false,"continent":"Asia"},"Hungary":{"id":348,"visited":false,"continent":"Europe"},"Iceland":{"id":352,"visited":false,"continent":"Europe"},"India":{"id":356,"visited":false,"continent":"Asia"},"Indonesia":{"id":360,"visited":false,"continent":"Asia"},"Iran":{"id":364,"visited":false,"continent":"Asia"},"Iraq":{"id":368,"visited":false,"continent":"Asia"},"Ireland":{"id":372,"visited":false,"continent":"Europe"},"Israel":{"id":376,"visited":false,"continent":"Asia"},"Italy":{"id":380,"visited":true,"continent":"Europe"},"Côte d'Ivoire":{"id":384,"visited":false,"continent":"Africa"},"Jamaica":{"id":388,"visited":true,"continent":"North America"},"Japan":{"id":392,"visited":false,"continent":"Asia"},"Kazakhstan":{"id":398,"visited":false,"continent":"Asia"},"Jordan":{"id":400,"visited":false,"continent":"Asia"},"Kenya":{"id":404,"visited":false,"continent":"Africa"},"North Korea":{"id":408,"visited":false,"continent":"Asia"},"South Korea":{"id":410,"visited":false,"continent":"Asia"},"Kuwait":{"id":414,"visited":false,"continent":"Asia"},"Kyrgyzstan":{"id":417,"visited":false,"continent":"Asia"},"Laos":{"id":418,"visited":false,"continent":"Asia"},"Lebanon":{"id":422,"visited":false,"continent":"Asia"},"Lesotho":{"id":426,"visited":false,"continent":"Africa"},"Latvia":{"id":428,"visited":false,"continent":"Europe"},"Liberia":{"id":430,"visited":false,"continent":"Africa"},"Libya":{"id":434,"visited":false,"continent":"Africa"},"Liechtenstein":{"id":438,"visited":false,"continent":"Europe"},"Lithuania":{"id":440,"visited":false,"continent":"Europe"},"Luxembourg":{"id":442,"visited":false,"continent":"Europe"},"Macao":{id:446,visited:false,continent:"Europe"},"Madagascar":{"id":450,"visited":false,"continent":"Africa"},"Malawi":{"id":454,"visited":false,"continent":"Africa"},"Malaysia":{"id":458,"visited":false,"continent":"Asia"},"Maldives":{"id":462,"visited":false,"continent":"Asia"},"Mali":{"id":466,"visited":false,"continent":"Africa"},"Malta":{"id":470,"visited":false,"continent":"Europe"},"Martinique":{"id":474,"visited":false,"continent":"North America"},"Mauritania":{"id":478,"visited":false,"continent":"Africa"},"Mauritius":{"id":480,"visited":false,"continent":"Africa"},"Mexico":{"id":484,"visited":true,"continent":"North America"},"Monaco":{"id":492,"visited":false,"continent":"Europe"},"Mongolia":{"id":496,"visited":false,"continent":"Asia"},"Moldova, Republic of":{"id":498,"visited":false,"continent":"Europe"},"Montenegro":{"id":499,"visited":false,"continent":"Europe"},"Montserrat":{"id":500,"visited":false,"continent":"North America"},"Morocco":{"id":504,"visited":false,"continent":"Africa"},"Mozambique":{"id":508,"visited":false,"continent":"Africa"},"Oman":{"id":512,"visited":false,"continent":"Asia"},"Namibia":{"id":516,"visited":false,"continent":"Africa"},"Nauru":{"id":520,"visited":false,"continent":"Oceania"},"Nepal":{"id":524,"visited":false,"continent":"Asia"},"Netherlands":{"id":528,"visited":false,"continent":"Europe"},"Curaçao":{"id":531,"visited":true,"continent":"South America"},"Aruba":{"id":533,"visited":true,"continent":"South America"},"Sint Maarten (Dutch part)":{"id":534,"visited":true,"continent":"North America"},"Bonaire":{"id":535,"visited":false,"continent":"South America"},"Sint Eustatius":{"id":536,"visited":false,"continent":"North America"},"Saba":{"id":537,"visited":false,"continent":"North America"},"New Caledonia":{"id":540,"visited":false,"continent":"Oceania"},"Vanuatu":{"id":548,"visited":false,"continent":"Oceania"},"New Zealand":{"id":554,"visited":false,"continent":"Oceania"},"Nicaragua":{"id":558,"visited":false,"continent":"North America"},"Niger":{"id":562,"visited":false,"continent":"Africa"},"Nigeria":{"id":566,"visited":false,"continent":"Africa"},"Niue":{"id":570,"visited":false,"continent":"Oceania"},"Norfolk Island":{"id":574,"visited":false,"continent":"Oceania"},"Norway":{"id":578,"visited":false,"continent":"Europe"},"Northern Mariana Islands":{"id":580,"visited":false,"continent":"Oceania"},"Micronesia, Federated States of":{"id":583,"visited":false,"continent":"Oceania"},"Marshall Islands":{"id":584,"visited":false,"continent":"Oceania"},"Palau":{"id":585,"visited":false,"continent":"Oceania"},"Pakistan":{"id":586,"visited":false,"continent":"Asia"},"Panama":{"id":591,"visited":true,"continent":"North America"},"Papua New Guinea":{"id":598,"visited":false,"continent":"Oceania"},"Paraguay":{"id":600,"visited":false,"continent":"South America"},"Peru":{"id":604,"visited":false,"continent":"South America"},"Philippines":{"id":608,"visited":false,"continent":"Asia"},"Pitcairn":{"id":612,"visited":false,"continent":"Oceania"},"Poland":{"id":616,"visited":false,"continent":"Europe"},"Portugal":{"id":620,"visited":false,"continent":"Europe"},"Guinea-Bissau":{"id":624,"visited":false,"continent":"Africa"},"Timor-Leste":{"id":626,"visited":false,"continent":"Asia"},"Puerto Rico":{"id":630,"visited":true,"continent":"North America"},"Qatar":{"id":634,"visited":false,"continent":"Asia"},"Romania":{"id":642,"visited":false,"continent":"Europe"},"Russia":{"id":643,"visited":false,"continent":"Asia"},"Rwanda":{"id":646,"visited":false,"continent":"Africa"},"Saint Barthélemy":{"id":652,"visited":false,"continent":"North America"},"Saint Helena, Ascension and Tristan da Cunha":{"id":654,"visited":false,"continent":"South America"},"Saint Kitts and Nevis":{"id":659,"visited":false,"continent":"North America"},"Anguilla":{"id":660,"visited":false,"continent":"North America"},"Saint Lucia":{"id":662,"visited":true,"continent":"North America"},"Saint Martin (French part)":{"id":663,"visited":true,"continent":"North America"},"Saint Pierre and Miquelon":{"id":666,"visited":false,"continent":"North America"},"Saint Vincent and the Grenadines":{"id":670,"visited":false,"continent":"North America"},"San Marino":{"id":674,"visited":false,"continent":"Europe"},"Sao Tome and Principe":{"id":678,"visited":false,"continent":"Africa"},"Saudi Arabia":{"id":682,"visited":false,"continent":"Asia"},"Senegal":{"id":686,"visited":false,"continent":"Africa"},"Serbia":{"id":688,"visited":false,"continent":"Europe"},"Seychelles":{"id":690,"visited":false,"continent":"Africa"},"Sierra Leone":{"id":694,"visited":false,"continent":"Africa"},"Singapore":{"id":702,"visited":false,"continent":"Asia"},"Slovakia":{"id":703,"visited":false,"continent":"Europe"},"Vietnam":{"id":704,"visited":false,"continent":"Asia"},"Slovenia":{"id":705,"visited":false,"continent":"Europe"},"Somalia":{"id":706,"visited":false,"continent":"Africa"},"South Africa":{"id":710,"visited":false,"continent":"Africa"},"Zimbabwe":{"id":716,"visited":false,"continent":"Africa"},"Spain":{"id":724,"visited":false,"continent":"Europe"},"South Sudan":{"id":728,"visited":false,"continent":"Africa"},"Sudan":{"id":729,"visited":false,"continent":"Africa"},"Western Sahara":{"id":732,"visited":false,"continent":"Africa"},"Suriname":{"id":740,"visited":false,"continent":"South America"},"Svalbard and Jan Mayen":{"id":744,"visited":false,"continent":"Europe"},"Swaziland":{"id":748,"visited":false,"continent":"Africa"},"Sweden":{"id":752,"visited":false,"continent":"Europe"},"Switzerland":{"id":756,"visited":false,"continent":"Europe"},"Syrian Arab Republic":{"id":760,"visited":false,"continent":"Asia"},"Tajikistan":{"id":762,"visited":false,"continent":"Asia"},"Thailand":{"id":764,"visited":false,"continent":"Asia"},"Togo":{"id":768,"visited":false,"continent":"Africa"},"Tonga":{"id":776,"visited":false,"continent":"Oceania"},"Trinidad and Tobago":{"id":780,"visited":false,"continent":"South America"},"United Arab Emirates":{"id":784,"visited":false,"continent":"Asia"},"Tunisia":{"id":788,"visited":false,"continent":"Africa"},"Turkey (Europe)":{"id":792,"visited":true,"continent":"Europe"},"Turkey (Asia)":{"id":793,"visited":false,"continent":"Asia"},"Turkmenistan":{"id":795,"visited":false,"continent":"Asia"},"Turks and Caicos Islands":{"id":796,"visited":true,"continent":"North America"},"Tuvalu":{"id":798,"visited":false,"continent":"Oceania"},"Uganda":{"id":800,"visited":false,"continent":"Africa"},"Ukraine":{"id":804,"visited":false,"continent":"Europe"},"Macedonia":{"id":807,"visited":false,"continent":"Europe"},"Egypt":{"id":818,"visited":false,"continent":"Africa"},"United Kingdom":{"id":826,"visited":false,"continent":"Europe"},"Guernsey":{id:831,visited:false,continent:"Europe"},"Jersey":{"id":832,"visited":false,"continent":"Europe"},"Isle of Man":{id:833,visited:false,continent:"Europe"},"Tanzania":{"id":834,"visited":false,"continent":"Africa"},"Virgin Islands, U.S.":{"id":850,"visited":true,"continent":"North America"},"Burkina Faso":{"id":854,"visited":false,"continent":"Africa"},"Uruguay":{"id":858,"visited":false,"continent":"South America"},"Uzbekistan":{"id":860,"visited":false,"continent":"Asia"},"Venezuela, Bolivarian Republic of":{"id":862,"visited":false,"continent":"South America"},"Wallis and Futuna":{"id":876,"visited":false,"continent":"Oceania"},"Samoa":{"id":882,"visited":false,"continent":"Oceania"},"Yemen":{"id":887,"visited":false,"continent":"Asia"},"Zambia":{"id":894,"visited":false,"continent":"Africa"},"Corsica":{"id":900,"visited":false,"continent":"Europe"},"Reunion":{"id":901,"visited":false,"continent":"Africa"},"Kosovo":{"id":902,"visited":false,"continent":"Europe"}};
var jv_states = {"Alabama":{"id":"01","visited":false},"Alaska":{"id":"02","visited":true},"Arizona":{"id":"04","visited":false},"Arkansas":{"id":"05","visited":false},"California":{"id":"06","visited":false},"Colorado":{"id":"08","visited":false},"Connecticut":{"id":"09","visited":true},"Delaware":{"id":"10","visited":false},"Florida":{"id":"12","visited":true},"Georgia (U.S. state)":{"id":"13","visited":false},"Hawaii":{"id":"15","visited":false},"Idaho":{"id":"16","visited":false},"Illinois":{"id":"17","visited":false},"Indiana":{"id":"18","visited":false},"Iowa":{"id":"19","visited":false},"Kansas":{"id":"20","visited":false},"Kentucky":{"id":"21","visited":false},"Louisiana":{"id":"22","visited":false},"Maine":{"id":"23","visited":true},"Maryland":{"id":"24","visited":true},"Massachusetts":{"id":"25","visited":true},"Michigan":{"id":"26","visited":false},"Minnesota":{"id":"27","visited":false},"Mississippi":{"id":"28","visited":false},"Missouri":{"id":"29","visited":false},"Montana":{"id":"30","visited":false},"Nebraska":{"id":"31","visited":false},"Nevada":{"id":"32","visited":false},"New Hampshire":{"id":"33","visited":true},"New Jersey":{"id":"34","visited":true},"New Mexico":{"id":"35","visited":false},"New York":{"id":"36","visited":true},"North Carolina":{"id":"37","visited":false},"North Dakota":{"id":"38","visited":false},"Ohio":{"id":"39","visited":true},"Oklahoma":{"id":"40","visited":false},"Oregon":{"id":"41","visited":false},"Pennsylvania":{"id":"42","visited":true},"Rhode Island":{"id":"44","visited":true},"South Carolina":{"id":"45","visited":false},"South Dakota":{"id":"46","visited":false},"Tennessee":{"id":"47","visited":false},"Texas":{"id":"48","visited":false},"Utah":{"id":"49","visited":false},"Vermont":{"id":"50","visited":true},"Virginia":{"id":"51","visited":true},"Washington":{"id":"53","visited":true},"West Virginia":{"id":"54","visited":false},"Wisconsin":{"id":"55","visited":false},"Wyoming":{"id":"56","visited":false}};
var jv_continents = {"Africa":0,"Asia":0,"Europe":3,"North America":21,"Oceania":0,"South America":2,"Antarctica":0};